version: "3.3"
services:
    web:
        build: .
        command: flask run --host=0.0.0.0
        ports:
        - "5000:5000"
        volumes:
        - .:/f
        links:
        - db
    db:
        image: mongo:latest
        command: mongodb start
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/usr/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./db:/usr/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
