version: "3.3"
services:
    web:
        image: "jcrecio/flipi-requestcontainer:latest"
        command: flask run --host=0.0.0.0
        ports:
            - "5000:5000"
        networks:
            - appnet
        volumes:
            - .:/requestcontainer
        links:
            - requestcontainerdatabase
    requestcontainerdatabase:
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - appnet
networks:
    appnet:
        driver: overlay