version: "3.5"

networks:
      overnet:
        external:
            name: overnet

services:
    web:
        image: "jcrecio/flipi-requestcontainer:latest"
        command: flask run --host=0.0.0.0
        networks:
            - overnet
        ports:
            - "5000:5000"
        volumes:
            - .:/requestcontainer
    requestcontainerdatabase:
        image: mongo:latest
        networks:
            - overnet
        ports:
            - "27017:27017"