version: "3.5"

networks:
    flipinet:
      external:
        name: flipinet
    internal: 
        name: internal

services:
    web:
        image: "jcrecio/flipi-requestcontainer:latest"
        command: flask run --host=0.0.0.0
        networks:
            - flipinet
            - internal
        ports:
            - "5000:5000"
        volumes:
            - .:/requestcontainer
    requestcontainerdatabase:
        image: mongo:latest
        networks:
            - flipinet
            - internal
        ports:
            - "27017:27017"