version: "3.3"
services:
    web:
        build: .
        command: flask run --host=0.0.0.0
        ports:
        - "5000:5000"
        volumes:
        - .:/f
        links:
        - db
    db:
        image: mongo:3.0.2