version: "3.3"
services:
    web:
        build: .
        command: flask run --host=0.0.0.0
        ports:
            - "5000:5000"
        volumes:
            - .:/requestcontainer
        links:
            - requestcontainerdatabase
    requestcontainerdatabase:
        image: mongo:latest
        deploy:
            restart_policy:
                condition: always
        ports:
            - "27017:27017"
